### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by halvorboe** [tihlde/Nettside#13]

**Comment by jorgenbele** [comment]
Det er vel sikkert være nødvendig med flere typer tilstandsindikatorer uansett, så vi kan i alle fall starte med en spinner, etter som at den er mest generell. Når det er sagt så er jo ikke en spinner særlig nyttig for å vise "progress".

**Comment by Andorr** [comment]
Kan jo ha to komponenter. En for progress, som da viser faktisk en progress-value, og man kan velge om den er horisontal eller sirkulær for eksempel? Også har vi en som heter Loading, som er en spinner. Hva tenker du?

**Comment by jorgenbele** [comment]
Ja, det høres greit ut.

**Comment by halvorboe** [comment]
Burde være horisontal

Få Outlook for iOS<https://aka.ms/o0ukef>
________________________________
