### ISSUE TITLE
News

### ISSUE THREAD

**Issue by halvorboe** [tihlde/Nettside#3]

**Comment by Andorr** [comment]
Antar at denne komponenten skal displaye et nyhetsartikkel.

Den skal derfor inneholde følgende ting som skal legges inn som props:
* Et bilde
* En tittel
* En deskriptiv-tekst om nyheten.
* Tidspunkt og dato postet (?)

Denne komponenten skal også være fleksibel i størrelse på grunn av sin posisjon i et grid.
* Antar at den skal extende en GridItem-component.
* Innholdet (bilder, tekst, tittel...osv) må tilpasse seg størrelsen den får av GridItem

**Comment by halvorboe** [comment]
Mekker det i morgen
