### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by halvorboe** [tihlde/Nettside#4]

**Comment by WilliamCJacobsen** [comment]
Den skal da inneholde disse komponentene: 
1.  Arrangementer/Hjem 
2.  Bedrifter
3. Om Tihlde
Jeg tenker den blå fargen som halvor har på den hero siden hans er perfekt. Jeg likte også at den retractet når man bladde nedover. men istenfor at den retracter helt så kan den heller bli transparent. også når man hovrer musen over så vil den gå tilbake til den gamle fargen sin.
Så den fader den frem og tilbake. 

egghvit skrift hadde vært perfekt tror jeg, og en font med IKKE sarif

**Comment by HunkyMcHunkins** [comment]
Samme som William, men også et lite profil-ikon til høyre for innlogging, innstillinger og utlogging. Mulig med en "Ny student" også men det kan ligge i "Om Tihlde". Men viktigst er at det ikke blir alt for mye og uoversiktlig.

**Comment by HunkyMcHunkins** [comment]
Samme som William, men også et lite profil-ikon til høyre for innlogging, innstillinger og utlogging. Mulig med en "Ny student" også men det kan ligge i "Om Tihlde". Men viktigst er at det ikke blir alt for mye og uoversiktlig. Tenkte også en søke-funksjon for å finne spesifikke ting.
