### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by jorgenbele** [tihlde/Nettside#7]

**Comment by jorgenbele** [comment]
Jeg er ikke helt sikker på hva _headeren_ skal inneholde. Er det ment at _headeren_ skal inneholde _navbaren_, eller skal det være noe helt annet? @SveinungOverland

**Comment by SveinungOverland** [comment]
Har ingen anelse, spørs vel om vi skal lage noe anno 2005, med store tittler og tekst over navbaren. @jorgenbele

**Comment by jorgenbele** [comment]
Det er mulig det er ment at det skal fungere på lik måte som dette: [react-native-elements header]( https://react-native-training.github.io/react-native-elements/docs/header.html) @SveinungOverland

**Comment by SveinungOverland** [comment]
Mulig, men det er for React Native, er usikker på hvor mye vi kan gjøre med en nettside utenom å bruke en theme color meta tag
