### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by jorgenbele** [tihlde/Nettside#9]

**Comment by Andorr** [comment]
Antar at denne komponenten skal:

- Inneholde informasjon om hvordan man kan kontakte TIHLDE.
- Inneholde lenker til TIHLDE sine sider på sosiale medier (Facebook, Twitter, LinkedIn...hva har de(?)).

**Comment by WilliamCJacobsen** [comment]
Jeg kan starte med denne i kveld 🥇
